"""Bitstream / FPGA configuration layer identifier catalog."""
from catalogs import make_entry

LAYER = "bit"


def _e(i, m, d, s, b, ev):
    return make_entry(i, LAYER, m, d, s, b, ev)


ENTRIES = [
    _e("BIT-001-FORMAT", "header", "Xilinx BIT bitstream format", "confirmed", None, "file magic"),
    _e("BIT-002-FILE-SIZE", "header", "131046 bytes total", "confirmed", None, "wc -c"),
    _e("BIT-003-SHA256", "header", "63cd3874297407bceedb524909d919dd35ba8a16639573a1af81721aed4fc3f5", "confirmed", None, "sha256sum"),
    _e("BIT-004-SOURCE-DESIGN", "header", "Source NCD design name (redacted in manifests)", "confirmed", None, "bitstream section a"),
    _e("BIT-005-TARGET-DEVICE", "header", "Spartan-3 XC3S200", "confirmed", None, "section a"),
    _e("BIT-006-PACKAGE", "header", "FT256 package", "confirmed", None, "device string"),
    _e("BIT-007-BUILD-DATE", "header", "2011/06/10", "confirmed", None, "section b"),
    _e("BIT-008-BUILD-TIME", "header", "12:44:47", "confirmed", None, "section b"),
    _e("BIT-009-USER-ID", "header", "0xFFFFFFFF", "confirmed", None, "section b"),
    _e("BIT-010-DATA-LENGTH", "header", "Config data 0x1FF88 bytes", "confirmed", None, "section d"),
    _e("BIT-011-SECTION-A", "header", "Section a device identifier", "confirmed", None, "BIT parser"),
    _e("BIT-012-SECTION-B", "header", "Section b design metadata", "confirmed", None, "BIT parser"),
    _e("BIT-013-SECTION-C", "header", "Section c part name", "confirmed", None, "BIT parser"),
    _e("BIT-014-SECTION-D", "header", "Section d configuration data", "confirmed", None, "BIT parser"),
    _e("BIT-015-CONFIG-OFFSET", "header", "Configuration data byte offset 94", "confirmed", None, "frame_summary.json"),
    _e("BIT-SYNC-WORD", "packet", "Sync word 0xAA995566", "confirmed", None, "frame_summary.config_data.sync_word"),
    _e("BIT-IDCODE", "packet", "IDCODE 0x01414093 (Spartan-3 XC3S200)", "confirmed", None, "frame_summary.packet_stream.registers.IDCODE"),
    _e("BIT-FLR", "packet", "Frame Length Register = 52 words", "confirmed", None, "frame_summary.packet_stream.registers.FLR"),
    _e("BIT-COR", "packet", "COR register 0x40003FE5", "confirmed", None, "frame_summary.packet_stream.registers.COR"),
    _e("BIT-CRC", "packet", "CRC value 0x00005F57", "confirmed", None, "frame_summary.packet_stream.registers.CRC"),
    _e("BIT-CMD-SEQUENCE", "packet", "RCRC→SWITCH→WCFG→GRESTORE→DGHIGH→START→DESYNCH", "confirmed", None, "frame_summary.packet_stream.cmd_sequence"),
    _e("BIT-FDRI-WORD-COUNT", "packet", "FDRI payload 32648 words", "confirmed", None, "frame_summary.packet_stream.fdri.word_count"),
    _e("BIT-FRAME-COUNT-EST", "packet", "Estimated 627 configuration frames (FDRI/FLR split)", "confirmed", None, "frame_summary.frame_analysis.estimated_frame_count"),
    _e("FRM-001-FORMAT", "frame", "Spartan-3 Type-1/Type-2 frame format", "candidate", "帧解析未完全验证", "UG332"),
    _e("FRM-002-COUNT", "frame", "Estimated 627 configuration frames", "candidate", "FDRI非整除FLR", "frame_summary"),
    _e("FRM-003-WORD-WIDTH", "frame", "16-bit frame words", "confirmed", None, "Spartan-3 spec"),
    _e("FRM-004-TYPE1", "frame", "Type-1 write frames", "candidate", "计数未闭合", "frame scan"),
    _e("FRM-005-TYPE2", "frame", "Type-2 noop/pad frames", "candidate", "计数未闭合", "frame scan"),
    _e("FRM-006-STARTUP", "frame", "Startup clock cycles", "unknown", "需帧级解码", None),
    _e("FRM-007-CRC", "frame", "CRC register 0x00005F57", "confirmed", None, "frame_summary"),
    _e("FRM-008-FAR", "frame", "Frame Address Register targets", "unknown", "需完整解析", None),
    _e("FRM-009-PIPELINE", "frame", "Pipeline register settings", "unknown", None, None),
    _e("FRM-010-PADDING", "frame", "Padding/unused config bits", "candidate", None, "entropy analysis"),
    _e("FRM-011-FAR-WRITE-COUNT", "frame", "Single explicit FAR write (0x00000000)", "confirmed", None, "scan_spartan3_frames.py / frame_deep.json"),
    _e("FRM-012-FAR-COLUMN-ADDR", "frame", "FAR Column Address field = 0 (logic & I/O block)", "confirmed", None, "frame_deep.json (XAPP452 Fig.2 decode)"),
    _e("FRM-013-FAR-MAJOR-MINOR", "frame", "FAR start Major=0 / Minor=0", "confirmed", None, "frame_deep.json"),
    _e("FRM-014-FAR-AUTOINC", "frame", "Per-frame FAR via internal auto-increment", "candidate", "逐帧地址由器件内部自增，未在位流中编码，不可重建", "XAPP452 frame addressing"),
    _e("FRM-015-FRAME-LENGTH", "frame", "Frame length 52 words (FLR register)", "confirmed", None, "frame_deep.json register inventory"),
    _e("FRM-016-FRAME-COUNT-EST", "frame", "Estimated 627 configuration frames", "candidate", "FDRI 字数非 FLR 整数倍，计数为估计值", "frame_deep.json"),
    _e("FRM-017-PAD-FRAME", "frame", "Trailing pad frame per spec", "candidate", "尾帧为填充帧，边界未逐字验证", "UG332/XAPP452"),
    _e("FRM-018-COLUMN-ADDR-DIST", "frame", "Explicit frame writes confined to Column Address 0", "candidate", "块类型分布仅反映显式写入，自增部分未知", "frame_deep.json histogram"),
    _e("FRM-019-LOGIC-COLUMN-EST", "frame", "~33 logic columns (candidate estimate)", "candidate", "按 CLB/IOI 每列 19 帧估算，逐器件列表未知", "frame_deep.json"),
    _e("FRM-020-REG-WRITE-SET", "frame", "Config register write set CMD/FLR/COR/IDCODE/MASK/FAR/CTL/CRC", "confirmed", None, "frame_deep.json register inventory"),
    _e("IOB-001-ACTIVE-COUNT", "iob", "Candidate IOB config words: 223", "candidate", "启发式边缘列", "frame_summary candidate_iob_config_words"),
    _e("IOB-002-INPUTS", "iob", "Input-configured IOB pins", "unknown", None, None),
    _e("IOB-003-OUTPUTS", "iob", "Output-configured IOB pins", "unknown", None, None),
    _e("IOB-004-BIDIR", "iob", "Bidirectional IOB pins", "unknown", None, None),
    _e("IOB-005-USB-FIFO", "iob", "USB Slave FIFO bus pins", "hypothesis", "需引脚对照", "pin_hypothesis.json"),
    _e("IOB-006-ADC-IF", "iob", "ADC interface pins", "hypothesis", "需引脚对照", "pin_hypothesis.json"),
    _e("IOB-007-RELAY-GPIO", "iob", "Relay control GPIO", "hypothesis", "需切换实验", "pin_hypothesis.json"),
    _e("IOB-008-CLOCK", "iob", "Global clock input pins", "unknown", None, None),
    _e("IOB-009-RESET", "iob", "Reset input pins", "unknown", None, None),
    _e("IOB-010-UNUSED", "iob", "Unconfigured pins", "unknown", None, None),
    _e("IOB-011-BANK-0", "iob", "IO Bank 0 config", "unknown", None, None),
    _e("IOB-012-BANK-1", "iob", "IO Bank 1 config", "unknown", None, None),
    _e("IOB-013-BANK-2", "iob", "IO Bank 2 config", "unknown", None, None),
    _e("IOB-014-BANK-3", "iob", "IO Bank 3 config", "unknown", None, None),
    _e("IOB-015-PULL", "iob", "Pull-up/down settings", "unknown", None, None),
    _e("CLK-001-GCLK", "clock", "Global clock buffer usage", "unknown", None, None),
    _e("CLK-002-DIST", "clock", "Clock tree distribution", "unknown", None, None),
    _e("CLK-003-DLL", "clock", "DLL configuration", "unknown", None, None),
    _e("CLK-004-RESET", "clock", "Global reset network", "unknown", None, None),
    _e("CLK-005-DOMAINS", "clock", "Clock domain count", "unknown", None, None),
    _e("MEM-001-BRAM", "memory", "Block RAM instances", "unknown", None, None),
    _e("MEM-002-BRAM-INIT", "memory", "BRAM init content", "unknown", None, None),
    _e("MEM-003-DIST-RAM", "memory", "Distributed RAM", "unknown", None, None),
    _e("MEM-004-FIFO", "memory", "FIFO blocks", "hypothesis", "需BRAM解码", "architecture expectation"),
    _e("MEM-005-ROM", "memory", "ROM init tables", "unknown", None, None),
    _e("FRM-011-FAR-DIST", "frame", "FAR address value distribution", "candidate", "启发式解码", "frame_deep.json"),
    _e("FRM-012-TYPE1-REG-TOP", "frame", "Top Type-1 register write targets", "candidate", "寄存器语义未映射", "frame_deep.json"),
    _e("FRM-013-ZERO-RATIO", "frame", "Zero-word padding ratio in config", "confirmed", None, "frame_deep.json"),
    _e("FRM-014-CLASS-COUNTS", "frame", "Frame word class histogram", "candidate", None, "frame_deep.json"),
    _e("FRM-015-IO-BLOCK-WRITES", "frame", "IO block FAR writes", "unknown", "需FAR解码", None),
    _e("FRM-016-CLB-BLOCK-WRITES", "frame", "CLB block FAR writes", "unknown", "需FAR解码", None),
    _e("FRM-017-BRAM-BLOCK-WRITES", "frame", "BRAM block FAR writes", "unknown", "需FAR解码", None),
    _e("FRM-018-CONFIG-ORDER", "frame", "Configuration write ordering", "unknown", None, None),
    _e("FRM-019-DONE-PIPE", "frame", "DONE pipeline settings", "unknown", None, None),
    _e("FRM-020-WAKEUP", "frame", "Startup wakeup sequence", "unknown", None, None),
]
