"""Skill catalog."""

from __future__ import annotations

from .types import SkillDef

SKILLS: dict[str, SkillDef] = {
    "shield_bash": SkillDef(
        id="shield_bash",
        name="盾击",
        kind="gcd",
        range=1,
        power=80,
        description="对相邻目标造成伤害并提高仇恨。",
    ),
    "rampart": SkillDef(
        id="rampart",
        name="铁壁",
        kind="ogcd",
        range=0,
        power=0,
        description="2 回合减伤。",
        mit_duration=2,
    ),
    "provoke": SkillDef(
        id="provoke",
        name="挑衅",
        kind="ogcd",
        range=7,
        power=0,
        description="强制 Boss 以自身为主目标 1 回合。",
    ),
    "cure": SkillDef(
        id="cure",
        name="治疗",
        kind="gcd",
        range=7,
        power=0,
        heal=180,
        description="治疗单个友方。",
    ),
    "medica": SkillDef(
        id="medica",
        name="医技",
        kind="gcd",
        range=7,
        power=0,
        heal=90,
        aoe_radius=2,
        description="治疗范围内所有友方。",
    ),
    "benediction": SkillDef(
        id="benediction",
        name="天赐",
        kind="ogcd",
        range=7,
        power=0,
        heal=9999,
        description="将单个友方生命值恢复至满。",
    ),
    "fire": SkillDef(
        id="fire",
        name="火炎",
        kind="gcd",
        range=7,
        power=120,
        description="远程伤害；本回合未移动时伤害 +50%。",
    ),
    "blizzard": SkillDef(
        id="blizzard",
        name="冰结",
        kind="gcd",
        range=7,
        power=70,
        description="远程伤害并略微降低 Boss 下回合伤害。",
    ),
    "manaward": SkillDef(
        id="manaward",
        name="魔罩",
        kind="ogcd",
        range=0,
        power=0,
        description="2 回合减伤。",
        mit_duration=2,
    ),
    "straight_shot": SkillDef(
        id="straight_shot",
        name="强力射击",
        kind="gcd",
        range=7,
        power=95,
        description="远程伤害；吟游之歌期间伤害 +30%。",
    ),
    "mages_ballad": SkillDef(
        id="mages_ballad",
        name="魔人歌",
        kind="ogcd",
        range=0,
        power=0,
        description="3 回合内全队 GCD 伤害 +20%。",
    ),
    "repelling_shot": SkillDef(
        id="repelling_shot",
        name="后跃射",
        kind="ogcd",
        range=7,
        power=40,
        description="造成伤害并向后移动 1 格。",
    ),
    "interrupt": SkillDef(
        id="interrupt",
        name="打断",
        kind="ogcd",
        range=7,
        power=0,
        description="打断 Boss 读条。",
    ),
}
